#! /usr/bin/python3
import cgi
form = cgi.FieldStorage()
text1 = ""
text2 = ""
if "foo" in form:
    foo_info = form["foo"].value
    text1 = "Multipart form teser, part 2:"
else:
    text1 = "400 Bad Request"
    text2 = "The variable 'foo' is required"
print ("Content-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>multipart form step2</title>')
print ('</head>')
print ('<body>')
print ('<h2>%s</h2>' % text1)
print ('<h2>%s</h2>' % text2)
print ('<form action=/cgi-bin/multipart_form_step3 method=get>')
print ('<input type=hidden name=foo value=%s>' % foo_info)
print ('bar:<input type=text name=bar>')
print ('<input type=submit>')
print ('</form>')
print ('</body>')
print ('</html>')
