#! /usr/bin/python3
import cgi
form = cgi.FieldStorage()
text1 = ""
text2 = ""
text3 = ""
if "foo" in form:
    foo_info = form["foo"].value
    text1 = "Multipart form result:"
    text2 += "foo: " + foo_info + "</br>"
else:
    text1 = "400 Bad Request"
    text2 = "The variable 'foo' is required"
if "bar" in form:
    bar_info = form["bar"].value
    text1 = "Multipart form result:"
    text2 += "bar: " + bar_info + "</br>"
else:
    text1 = "400 Bad Request"
    text2 = "The variable 'bar' is required"
if "baz" in form:
    baz_info = form["baz"].value
    text1 = "Multipart form result:"
    text2 += "baz: " + baz_info + "</br>"
else:
    text1 = "400 Bad Request"
    text2 = "The variable 'baz' is required"
if "fred" in form:
    fred_info = form["fred"].value
    text1 = "Multipart form result:"
    text2 += "fred: " + fred_info + "</br>"
else:
    text1 = "400 Bad Request"
    text2 = "The variable 'fred' is required"
print ("Content-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>multipart form step5</title>')
print ('</head>')
print ('<body>')
print ('<p>%s</p>' % text1)
print ('<p>%s</p>' % text2)
print ('</body>')
print ('</html>')


