#! /usr/bin/python3
import cgi
form = cgi.FieldStorage()
text1 = ""
text2 = ""
if "foo" in form:
    foo_info = form["foo"].value
    text1 = "Multipart form teser, part 3:"
else:
    text1 = "400 Bad Request"
    text2 = "The variable 'foo' is required"
if "bar" in form:
    bar_info = form["bar"].value
    text1 = "Multipart form teser, part 3:"
else:
    text1 = "400 Bad Request"
    text2 = "The variable 'bar' is required"
if "baz" in form:
    baz_info = form["baz"].value
    text1 = "Multipart form teser, part 3:"
else:
    text1 = "400 Bad Request"
    text2 = "The variable 'baz' is required"
print ("Content-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>multipart form step4</title>')
print ('</head>')
print ('<body>')
print ('<h2>%s</h2>' % text1)
print ('<h2>%s</h2>' % text2)
print ('<form action=/cgi-bin/multipart_form_step5 method=get>')
print ('<input type=hidden name=foo value=%s>' % foo_info)
print ('<input type=hidden name=bar value=%s>' % bar_info)
print ('<input type=hidden name=baz value=%s>' % baz_info)
print ('fred:<input type=text name=fred>')
print ('<input type=submit>')
print ('</form>')
print ('</body>')
print ('</html>')
